version: "3.8"
services:
  next-with-javascript:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    tty: true
    working_dir: /app
    volumes:
      - .:/app:delegated
    environment:
      - PORT=3000
      - HOST=0.0.0.0
    ports:
      - 3001:3000
    command: bash -c 'yarn install && yarn dev'
  